apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: smart-contact-manager
spec:
  selector:
    matchLabels:
      app: smart-contact-manager
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: smart-contact-manager
    spec:
      containers:
        - name: smart-contact-manager
          image: shahdocker768/smart-contact-manager # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: smart-contact-managersvc
spec:
  selector:
    app: smart-contact-manager
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
